# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Sajad\AP_Dr_Rafiei\Finall project\Design-ejector-simulation-software\project\Createusername.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 350)
        MainWindow.setStyleSheet("background-color:     rgb(245,255,250);\n"
"background-color:     rgb(238,238,228);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.create_username = QtWidgets.QLineEdit(self.centralwidget)
        self.create_username.setGeometry(QtCore.QRect(210, 60, 200, 32))
        self.create_username.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(21,76,121);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"\n"
"\n"
"\n"
"")
        self.create_username.setText("")
        self.create_username.setObjectName("create_username")
        self.create_password = QtWidgets.QLineEdit(self.centralwidget)
        self.create_password.setGeometry(QtCore.QRect(210, 110, 200, 32))
        self.create_password.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(21,76,121);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"\n"
"\n"
"\n"
"")
        self.create_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.create_password.setObjectName("create_password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 10, 131, 25))
        self.label.setStyleSheet("font: 75 11pt \"Calibri (Body)\";\n"
"color:   rgb(21,76,121);\n"
" ")
        self.label.setObjectName("label")
        self.CreateButton = QtWidgets.QPushButton(self.centralwidget)
        self.CreateButton.setGeometry(QtCore.QRect(316, 270, 120, 28))
        self.CreateButton.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(60,179,113);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"\n"
"\n"
"\n"
"")
        self.CreateButton.setObjectName("CreateButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 60, 80, 25))
        self.label_2.setStyleSheet("font: 75 9pt \"Calibri (Body)\";\n"
"color:   rgb(21,76,121);\n"
" ")
        self.label_2.setObjectName("label_2")
        self.confir_password = QtWidgets.QLineEdit(self.centralwidget)
        self.confir_password.setGeometry(QtCore.QRect(210, 160, 200, 32))
        self.confir_password.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(21,76,121);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"\n"
"\n"
"\n"
"")
        self.confir_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confir_password.setObjectName("confir_password")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 110, 80, 25))
        self.label_3.setStyleSheet("font: 75 9pt \"Calibri (Body)\";\n"
"color:   rgb(21,76,121);\n"
" ")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 162, 141, 25))
        self.label_4.setStyleSheet("font: 75 9pt \"Calibri (Body)\";\n"
"color:   rgb(21,76,121);\n"
" ")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 212, 80, 25))
        self.label_5.setStyleSheet("font: 75 9pt \"Calibri (Body)\";\n"
"color:   rgb(21,76,121);\n"
" ")
        self.label_5.setObjectName("label_5")
        self.create_gmail = QtWidgets.QLineEdit(self.centralwidget)
        self.create_gmail.setGeometry(QtCore.QRect(210, 210, 200, 32))
        self.create_gmail.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(21,76,121);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"\n"
"\n"
"\n"
"")
        self.create_gmail.setText("")
        self.create_gmail.setObjectName("create_gmail")
        self.LoginpageButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginpageButton.setGeometry(QtCore.QRect(184, 270, 120, 28))
        self.LoginpageButton.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(60,179,113);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"\n"
"\n"
"\n"
"")
        self.LoginpageButton.setObjectName("LoginpageButton")
        self.label_4.raise_()
        self.create_username.raise_()
        self.create_password.raise_()
        self.label.raise_()
        self.CreateButton.raise_()
        self.label_2.raise_()
        self.confir_password.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.create_gmail.raise_()
        self.LoginpageButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.create_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.create_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label.setText(_translate("MainWindow", "Create Account"))
        self.CreateButton.setText(_translate("MainWindow", "Create User"))
        self.label_2.setText(_translate("MainWindow", "Username :"))
        self.confir_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "Password :"))
        self.label_4.setText(_translate("MainWindow", "confirm Password :"))
        self.label_5.setText(_translate("MainWindow", "Gmail :"))
        self.create_gmail.setPlaceholderText(_translate("MainWindow", "Gmail"))
        self.LoginpageButton.setText(_translate("MainWindow", "back to login page"))
