# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Sajad\AP_Dr_Rafiei\Finall project\Design-ejector-simulation-software\project\recovery_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(600, 237)
        Login.setStyleSheet("background-color:     rgb(245,255,250);\n"
"background-color:     rgb(238,238,228);\n"
"")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginpageButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginpageButton.setGeometry(QtCore.QRect(220, 160, 150, 25))
        self.LoginpageButton.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(60,179,113);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"\n"
"\n"
"\n"
"")
        self.LoginpageButton.setObjectName("LoginpageButton")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(200, 70, 200, 32))
        self.username.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(21,76,121);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"\n"
"\n"
"\n"
"")
        self.username.setText("")
        self.username.setObjectName("username")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 491, 25))
        self.label.setStyleSheet("font: 75 11pt \"Calibri (Body)\";\n"
"color:   rgb(21,76,121);\n"
" ")
        self.label.setObjectName("label")
        self.RecoveryButton = QtWidgets.QPushButton(self.centralwidget)
        self.RecoveryButton.setGeometry(QtCore.QRect(220, 130, 150, 25))
        self.RecoveryButton.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(60,179,113);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"\n"
"\n"
"\n"
"")
        self.RecoveryButton.setObjectName("RecoveryButton")
        self.username.raise_()
        self.label.raise_()
        self.RecoveryButton.raise_()
        self.LoginpageButton.raise_()
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.LoginpageButton.setText(_translate("Login", "back to login page"))
        self.username.setPlaceholderText(_translate("Login", "Username"))
        self.label.setText(_translate("Login", "please enter your username that we send you new password"))
        self.RecoveryButton.setText(_translate("Login", "recovery"))
