# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Sajad\AP_Dr_Rafiei\Finall project\Apps.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1268, 670)
        MainWindow.setStyleSheet("background-color: #F5F5F5;\n"
" \n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.history_tab = QtWidgets.QPushButton(self.centralwidget)
        self.history_tab.setGeometry(QtCore.QRect(40, 70, 70, 70))
        self.history_tab.setStyleSheet("border: none;")
        self.history_tab.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Sajad\\AP_Dr_Rafiei\\Finall project\\icon/history-36.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_tab.setIcon(icon)
        self.history_tab.setIconSize(QtCore.QSize(70, 70))
        self.history_tab.setObjectName("history_tab")
        self.simulation_tab = QtWidgets.QPushButton(self.centralwidget)
        self.simulation_tab.setGeometry(QtCore.QRect(40, 190, 70, 70))
        self.simulation_tab.setStyleSheet("border: none;")
        self.simulation_tab.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Sajad\\AP_Dr_Rafiei\\Finall project\\icon/5346252.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.simulation_tab.setIcon(icon1)
        self.simulation_tab.setIconSize(QtCore.QSize(70, 70))
        self.simulation_tab.setObjectName("simulation_tab")
        self.setting_tab = QtWidgets.QPushButton(self.centralwidget)
        self.setting_tab.setGeometry(QtCore.QRect(40, 300, 70, 70))
        self.setting_tab.setStyleSheet("border: none;")
        self.setting_tab.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Sajad\\AP_Dr_Rafiei\\Finall project\\icon/Settings-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_tab.setIcon(icon2)
        self.setting_tab.setIconSize(QtCore.QSize(70, 70))
        self.setting_tab.setObjectName("setting_tab")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(149, 30, 1050, 571))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setStyleSheet("background-color: #F5F5DC;\n"
"background-color: #F5F5F5;\n"
"background-color: #FFFFFF;\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 950, 311))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"\n"
"    background-color: #F5F5F5;\n"
"    alternate-background-color: #778899;\n"
"    border-color: #000000;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #F5F5F5    ;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color:#D3D3D3    ;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #F0F8FF    ;\n"
"    \n"
"}\n"
"")
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(449)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(49)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 30, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri (Body)")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 12pt \"Calibri (Body)\";\n"
"color:   rgb(21,76,121);")
        self.label.setObjectName("label")
        self.LoginButton = QtWidgets.QPushButton(self.tab)
        self.LoginButton.setGeometry(QtCore.QRect(530, 430, 211, 31))
        self.LoginButton.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: #708090    ;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:1px;\n"
"\n"
"\n"
"\n"
"")
        self.LoginButton.setObjectName("LoginButton")
        self.LoginButton_2 = QtWidgets.QPushButton(self.tab)
        self.LoginButton_2.setGeometry(QtCore.QRect(750, 430, 211, 31))
        self.LoginButton_2.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: #708090    ;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:1px;\n"
"\n"
"\n"
"\n"
"")
        self.LoginButton_2.setObjectName("LoginButton_2")
        self.tabWidget.addTab(self.tab, "")
        self.Simulation = QtWidgets.QWidget()
        self.Simulation.setObjectName("Simulation")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Simulation)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 1050, 571))
        font = QtGui.QFont()
        font.setFamily("Calibri (Body)")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setStyleSheet("font: 75 9pt \"Calibri (Body)\";\n"
"color:   rgb(21,76,121);\n"
"color: #000000;")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setUsesScrollButtons(False)
        self.tabWidget_2.setTabBarAutoHide(True)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 281, 30))
        self.label_2.setObjectName("label_2")
        self.gas_propertice_input = QtWidgets.QLineEdit(self.tab_3)
        self.gas_propertice_input.setGeometry(QtCore.QRect(330, 80, 100, 30))
        self.gas_propertice_input.setStyleSheet("border-bottom-color: rgb(0, 0, 0);")
        self.gas_propertice_input.setObjectName("gas_propertice_input")
        self.propertice_next = QtWidgets.QPushButton(self.tab_3)
        self.propertice_next.setGeometry(QtCore.QRect(760, 450, 160, 28))
        self.propertice_next.setStyleSheet("QPushButton {\n"
"    background-color: #778899    ;\n"
"    color: #FF0000;\n"
"    border-radius:6px;\n"
"    border-style: solid;\n"
"\n"
"}\n"
"")
        self.propertice_next.setObjectName("propertice_next")
        self.properties_table = QtWidgets.QTableWidget(self.tab_3)
        self.properties_table.setGeometry(QtCore.QRect(20, 160, 901, 271))
        self.properties_table.setStyleSheet("QTableWidget {\n"
"\n"
"    background-color: #F5F5F5;\n"
"    alternate-background-color: #778899;\n"
"    border-color: #000000;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #F5F5F5    ;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color:#D3D3D3    ;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #F0F8FF    ;\n"
"    \n"
"}\n"
"")
        self.properties_table.setRowCount(0)
        self.properties_table.setObjectName("properties_table")
        self.properties_table.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.properties_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.properties_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.properties_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.properties_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.properties_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.properties_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.properties_table.setHorizontalHeaderItem(6, item)
        self.properties_table.horizontalHeader().setDefaultSectionSize(160)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(120, 80, 800, 350))
        self.tableWidget_3.setStyleSheet("QTableWidget {\n"
"\n"
"    background-color: #F5F5F5;\n"
"    alternate-background-color: #778899;\n"
"    border-color: #000000;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #F5F5F5    ;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color:#D3D3D3    ;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #F0F8FF    ;\n"
"    \n"
"}\n"
"")
        self.tableWidget_3.setRowCount(12)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.tableWidget_3.horizontalHeader().setDefaultSectionSize(374)
        self.pushButton5_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton5_2.setGeometry(QtCore.QRect(760, 450, 160, 28))
        self.pushButton5_2.setStyleSheet("QPushButton {\n"
"    background-color: #778899    ;\n"
"    color: #b80000;\n"
"    border-radius:6px;\n"
"    border-style: solid;\n"
"\n"
"}\n"
"")
        self.pushButton5_2.setObjectName("pushButton5_2")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_4.setGeometry(QtCore.QRect(120, 80, 800, 350))
        self.tableWidget_4.setStyleSheet("QTableWidget {\n"
"\n"
"    background-color: #F5F5F5;\n"
"    alternate-background-color: #778899;\n"
"    border-color: #000000;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #F5F5F5    ;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color:#D3D3D3    ;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #F0F8FF    ;\n"
"    \n"
"}\n"
"")
        self.tableWidget_4.setRowCount(12)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(374)
        self.pushButton5_3 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton5_3.setGeometry(QtCore.QRect(760, 450, 160, 28))
        self.pushButton5_3.setStyleSheet("QPushButton {\n"
"    background-color: #778899    ;\n"
"    color: #b80000;\n"
"    border-radius:6px;\n"
"    border-style: solid;\n"
"\n"
"}\n"
"")
        self.pushButton5_3.setObjectName("pushButton5_3")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_3 = QtWidgets.QLabel(self.tab_6)
        self.label_3.setGeometry(QtCore.QRect(35, 60, 231, 30))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_2.setGeometry(QtCore.QRect(385, 60, 113, 28))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(385, 120, 113, 28))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.tab_6)
        self.label_4.setGeometry(QtCore.QRect(35, 120, 231, 30))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_4.setGeometry(QtCore.QRect(385, 180, 113, 28))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.tab_6)
        self.label_5.setGeometry(QtCore.QRect(35, 180, 321, 30))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_5.setGeometry(QtCore.QRect(385, 240, 113, 28))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtWidgets.QLabel(self.tab_6)
        self.label_6.setGeometry(QtCore.QRect(35, 240, 231, 30))
        self.label_6.setObjectName("label_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_6.setGeometry(QtCore.QRect(385, 300, 113, 28))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_7 = QtWidgets.QLabel(self.tab_6)
        self.label_7.setGeometry(QtCore.QRect(35, 300, 231, 30))
        self.label_7.setObjectName("label_7")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(390, 360, 113, 28))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_8 = QtWidgets.QLabel(self.tab_6)
        self.label_8.setGeometry(QtCore.QRect(40, 360, 261, 30))
        self.label_8.setObjectName("label_8")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_8.setGeometry(QtCore.QRect(390, 420, 113, 28))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_9 = QtWidgets.QLabel(self.tab_6)
        self.label_9.setGeometry(QtCore.QRect(40, 420, 231, 30))
        self.label_9.setObjectName("label_9")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_18.setGeometry(QtCore.QRect(890, 120, 113, 28))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(580, 120, 231, 30))
        self.label_19.setObjectName("label_19")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_19.setGeometry(QtCore.QRect(890, 180, 113, 28))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setGeometry(QtCore.QRect(580, 180, 231, 30))
        self.label_20.setObjectName("label_20")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_20.setGeometry(QtCore.QRect(890, 240, 113, 28))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setGeometry(QtCore.QRect(580, 240, 180, 30))
        self.label_21.setObjectName("label_21")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_21.setGeometry(QtCore.QRect(890, 330, 113, 28))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_22 = QtWidgets.QLabel(self.tab_6)
        self.label_22.setGeometry(QtCore.QRect(580, 300, 281, 81))
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName("label_22")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_17.setGeometry(QtCore.QRect(890, 60, 113, 28))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setGeometry(QtCore.QRect(580, 60, 231, 30))
        self.label_18.setObjectName("label_18")
        self.pushButton5_4 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton5_4.setGeometry(QtCore.QRect(850, 460, 160, 28))
        self.pushButton5_4.setStyleSheet("QPushButton {\n"
"    background-color: #778899    ;\n"
"    color: #b80000;\n"
"    border-radius:6px;\n"
"    border-style: solid;\n"
"\n"
"}\n"
"")
        self.pushButton5_4.setObjectName("pushButton5_4")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_5.setGeometry(QtCore.QRect(120, 80, 800, 350))
        self.tableWidget_5.setStyleSheet("QTableWidget {\n"
"\n"
"    background-color: #F5F5F5;\n"
"    alternate-background-color: #778899;\n"
"    border-color: #000000;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #F5F5F5    ;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color:#D3D3D3    ;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #F0F8FF    ;\n"
"    \n"
"}\n"
"")
        self.tableWidget_5.setRowCount(12)
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        self.tableWidget_5.horizontalHeader().setDefaultSectionSize(249)
        self.pushButton5_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton5_6.setGeometry(QtCore.QRect(760, 450, 160, 28))
        self.pushButton5_6.setStyleSheet("QPushButton {\n"
"    background-color: #778899    ;\n"
"    color: #b80000;\n"
"    border-radius:6px;\n"
"    border-style: solid;\n"
"\n"
"}\n"
"")
        self.pushButton5_6.setObjectName("pushButton5_6")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_6.setGeometry(QtCore.QRect(120, 80, 800, 350))
        self.tableWidget_6.setStyleSheet("QTableWidget {\n"
"\n"
"    background-color: #F5F5F5;\n"
"    alternate-background-color: #778899;\n"
"    border-color: #000000;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #F5F5F5    ;\n"
"}\n"
"\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color:#D3D3D3    ;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #F0F8FF    ;\n"
"    \n"
"}\n"
"")
        self.tableWidget_6.setRowCount(12)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        self.tableWidget_6.horizontalHeader().setDefaultSectionSize(374)
        self.pushButton5_5 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton5_5.setGeometry(QtCore.QRect(760, 450, 160, 28))
        self.pushButton5_5.setStyleSheet("QPushButton {\n"
"    background-color: #778899    ;\n"
"    color: #b80000;\n"
"    border-radius:6px;\n"
"    border-style: solid;\n"
"\n"
"}\n"
"")
        self.pushButton5_5.setObjectName("pushButton5_5")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tabWidget.addTab(self.Simulation, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 500, 550))
        self.groupBox_2.setStyleSheet("font: 87 11pt \"Roboto Black\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(40, 80, 271, 31))
        self.label_24.setObjectName("label_24")
        self.classic = QtWidgets.QPushButton(self.groupBox_2)
        self.classic.setGeometry(QtCore.QRect(40, 140, 31, 31))
        self.classic.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #d5d5d5\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"")
        self.classic.setText("")
        self.classic.setObjectName("classic")
        self.dark_blue = QtWidgets.QPushButton(self.groupBox_2)
        self.dark_blue.setGeometry(QtCore.QRect(40, 200, 31, 31))
        self.dark_blue.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #162d44\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"")
        self.dark_blue.setText("")
        self.dark_blue.setObjectName("dark_blue")
        self.mnjaromix = QtWidgets.QPushButton(self.groupBox_2)
        self.mnjaromix.setGeometry(QtCore.QRect(40, 260, 31, 31))
        self.mnjaromix.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #7bd3a3\n"
"        );\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"")
        self.mnjaromix.setText("")
        self.mnjaromix.setObjectName("mnjaromix")
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setGeometry(QtCore.QRect(90, 140, 71, 31))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(90, 200, 91, 31))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(90, 260, 121, 31))
        self.label_27.setStyleSheet("")
        self.label_27.setObjectName("label_27")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget.addTab(self.tab_9, "")
        self.setting_tab.raise_()
        self.tabWidget.raise_()
        self.history_tab.raise_()
        self.simulation_tab.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1268, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        self.label.setText(_translate("MainWindow", "You can see you history of simulations here :"))
        self.LoginButton.setText(_translate("MainWindow", "Open simulation"))
        self.LoginButton_2.setText(_translate("MainWindow", "Open new simulation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "History"))
        self.label_2.setText(_translate("MainWindow", "The number of types of injected gas :"))
        self.propertice_next.setText(_translate("MainWindow", "Next >"))
        item = self.properties_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Molecular Weight"))
        item = self.properties_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mole fraction"))
        item = self.properties_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Gas constant"))
        item = self.properties_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Enthalpy of formation"))
        item = self.properties_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Constant A"))
        item = self.properties_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Constant B"))
        item = self.properties_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Constant C"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Gas Properties"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Specific Heat"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Temperature (R)"))
        self.pushButton5_2.setText(_translate("MainWindow", "Next >"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Specific heat-gas"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Specific Enthalpy"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Temperature (R)"))
        self.pushButton5_3.setText(_translate("MainWindow", "Next >"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Enthalpy-gas"))
        self.label_3.setText(_translate("MainWindow", "Environment Temperature(R) :"))
        self.label_4.setText(_translate("MainWindow", "Environment Pressure(Psig) :"))
        self.label_5.setText(_translate("MainWindow", "Installation height of operating valve(Mft) : "))
        self.label_6.setText(_translate("MainWindow", "Bellows Pressure(Psig) :"))
        self.label_7.setText(_translate("MainWindow", "Fenrit Bellows tension(Psig) :"))
        self.label_8.setText(_translate("MainWindow", "Cross section of Bellows(in^2) :"))
        self.label_9.setText(_translate("MainWindow", "Cross section of Pilot(in^2) :"))
        self.label_19.setText(_translate("MainWindow", "API gravity :"))
        self.label_20.setText(_translate("MainWindow", "Production tube(in) :"))
        self.label_21.setText(_translate("MainWindow", "Orifice diameter(in) :"))
        self.label_22.setText(_translate("MainWindow", "The angle of the axis of the production tube and the analos with the vertical axis :"))
        self.label_18.setText(_translate("MainWindow", "Water cut :"))
        self.pushButton5_4.setText(_translate("MainWindow", "Next >"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "GLS Properties "))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Injection pressure(Psig)"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Well pressure changes(Psig)"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Surface temperature (R)"))
        self.pushButton5_6.setText(_translate("MainWindow", "Next >"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "GLS Properties page 2"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Bellows Phenrite stress changes(Psig)"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Length change(in)"))
        self.pushButton5_5.setText(_translate("MainWindow", "Next >"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Bellow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Simulation), _translate("MainWindow", "Simulation"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Themes"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">You can choose your theme :</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Classic</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Dark</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Manjaro mix</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "setting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Page"))
import icons_rc
