# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Sajad\AP_Dr Rafiei\Finall project\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(600, 300)
        Login.setStyleSheet("background-color:     rgb(245,255,250);\n"
"background-color:     rgb(238,238,228);\n"
"")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setGeometry(QtCore.QRect(230, 190, 150, 25))
        self.LoginButton.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(60,179,113);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"\n"
"\n"
"\n"
"")
        self.LoginButton.setObjectName("LoginButton")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(200, 80, 200, 32))
        self.username.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(21,76,121);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"\n"
"\n"
"\n"
"")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(200, 130, 200, 32))
        self.password.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(21,76,121);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"\n"
"\n"
"\n"
"")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 10, 100, 25))
        self.label.setStyleSheet("font: 75 11pt \"Calibri (Body)\";\n"
"color:   rgb(21,76,121);\n"
" ")
        self.label.setObjectName("label")
        self.CreateButton = QtWidgets.QPushButton(self.centralwidget)
        self.CreateButton.setGeometry(QtCore.QRect(230, 220, 150, 25))
        self.CreateButton.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"background-color: rgb(60,179,113);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"\n"
"\n"
"\n"
"")
        self.CreateButton.setObjectName("CreateButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 40, 271, 25))
        self.label_2.setStyleSheet("font: 75 8pt \"Calibri (Body)\";\n"
"color:   rgb(21,76,121);\n"
"")
        self.label_2.setObjectName("label_2")
        self.username.raise_()
        self.password.raise_()
        self.label.raise_()
        self.CreateButton.raise_()
        self.label_2.raise_()
        self.LoginButton.raise_()
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.LoginButton.setText(_translate("Login", "Login"))
        self.username.setPlaceholderText(_translate("Login", "Username"))
        self.password.setPlaceholderText(_translate("Login", "Password"))
        self.label.setText(_translate("Login", "Login page"))
        self.CreateButton.setText(_translate("Login", "Create User"))
        self.label_2.setText(_translate("Login", "if you dont have account first create account"))
